# mock-hpc-job-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-hpc-job
  labels:
    app: mock-hpc-job
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mock-hpc-job
  template:
    metadata:
      labels:
        app: mock-hpc-job
    spec:
      containers:
        - name: mock-hpc-job
          image: mock-hpc-job:latest
          ports:
            - containerPort: 8080
