# hpcjob.crd.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: hpcjobs.kubernetes.hpc.com
spec:
  group: kubernetes.hpc.com
  names:
    kind: HPCJob
    listKind: HPCJobList
    plural: hpcjobs
    singular: hpcjob
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                jobName:
                  type: string
                state:
                  type: string
                  enum:
                    - Pending
                    - Running
                    - Completed
                    - Failed
                jobParams:
                  type: object
                  additionalProperties:
                    type: string
                image:
                  type: string
                replicas:
                  type: integer
            status:
              type: object
              properties:
                state:
                  type: string
                completionTime:
                  type: string
                  format: date-time
