apiVersion: kubernetes.hpc.com/v1
kind: HPCJob
metadata:
  name: mock-hpc-job
  namespace: default
spec:
  jobName: mock-hpc-job
  state: Pending
  image: mock-hpc-job:latest
  imagePullPolicy: IfNotPresent
  replicas: 1
  jobParams:
    param1: "job-id-1234"
    param2: "1000"
status:
  state: Pending
  completionTime: null 
