name: Build and Deploy HPCJob Controller to Minikube

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Deploy Controller to Minikube
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.1'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}

      # Build Docker image
      - name: Build controller image
        run: |
          docker build -t hpcjob-controller:${{ github.sha }} .

      # Save Docker image to tar file
      - name: Export controller image
        run: |
          docker save hpcjob-controller:${{ github.sha }} -o hpcjob-controller-${{ github.sha }}.tar

      # Set Minikube
      - name: Run Minikube
        run: |
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo mv minikube /usr/local/bin/
          sudo chmod +x /usr/local/bin/minikube
          minikube start --driver=docker

      - name: Load controller image into Minikube
        run: |
          minikube image load hpcjob-controller-${{ github.sha }}.tar

      - name: Replace controller image tag
        run: |
          IMAGE_TAG="hpcjob-controller:${{ github.sha }}"
          sed -i "/image:/s|hpc-controller|$IMAGE_TAG|g" k8s/controller-deployment.yaml

      # Deploy the controller to Minikube
      - name: Deploy resources to Minikube
        run: |
          kubectl apply -f k8s/crd.yaml
          kubectl apply -f k8s/controller-deployment.yaml
          kubectl apply -f k8s/hpcjob.yaml

      - name: Verify controller image in Minikube
        run: |
          minikube ssh -- docker images

      - name: Check Minikube resources
        run: |
          minikube ssh -- free -h
          minikube ssh -- df -h

      - name: Wait for deployment to be ready
        run: |
          kubectl wait --for=condition=available deployment/mock-hpc-job --namespace=default --timeout=200s

      # Verify controller is working
      - name: Check mock-hpc-job deployment
        run: |
          kubectl get pods --namespace=default
          kubectl logs -l app=mock-hpc-job --namespace=default
